wip: Stopping point

diff --git a/.local/bin/generate_imports b/.local/bin/generate_imports
--- a/.local/bin/generate_imports
+++ b/.local/bin/generate_imports
@@ -2,9 +2,25 @@
 
 set -eu
 
-# Required Variables
-tf_token="${TF_TOKEN:?}"
-organization_name="${TF_ORG_NAME:?}"
+# Check if the required utility `jq` is installed.
+command -v jq >/dev/null || {
+  echo "Error: jq is not installed." >&2
+  exit 1
+}
+
+# Check if the required `TF_TOKEN` environment variable is set.
+tf_token="${TF_TOKEN:?'parameter is null or not set. Use export TF_TOKEN="" to set this parameter.'}"
+
+# Get the HCP Terraform organization name from the required `hcp_terraform_organization_name` terraform variable.
+script_path="$(cd "$(dirname "$0")" && pwd)"
+tfvars_path="${script_path}/../../terraform.tfvars"
+
+[ -f "${tfvars_path}" ] || {
+  echo "Error: terraform.tfvars not found, unable to get the organization name." >&2
+  exit 1
+}
+
+organization_name="$(grep '^hcp_terraform_organization_name' "${tfvars_path}" | cut -d'=' -f2 | tr -d ' "')"
 
 # The owners team ID is used in the organization membership ID query, so
 # we assign it to a variable.
@@ -16,55 +32,21 @@ owners_team_id="$(
     jq -r '.data[] | select(.attributes.name == "owners") | .id'
 )"
 
-# Display the owners team ID.
-printf '%s\n' "Team ID               Team Name"
-printf '%s\n' "--------------------- ---------"
-printf '%s %s\n\n' "${owners_team_id}" "owners"
-
 # Display the organization membership IDs.
-printf '%s\n' "Org Membership ID   Username"
-printf '%s\n' "------------------- ----------------------------------------"
 curl --silent \
   --header "Authorization: Bearer ${tf_token}" \
   --header "Content-Type: application/vnd.api+json" \
   https://app.terraform.io/api/v2/teams/"${owners_team_id}" |
   jq -r '.data.relationships."organization-memberships".data[].id' |
   while read -r organization_membership_id; do
-    curl --silent \
+    email="$(curl --silent \
       --header "Authorization: Bearer ${tf_token}" \
       --header "Content-Type: application/vnd.api+json" \
       https://app.terraform.io/api/v2/organization-memberships/"${organization_membership_id}" |
-      jq -r '.data.relationships.user.data.id' |
-      while read -r user_id; do
-        username="$(curl --silent \
-          --header "Authorization: Bearer ${tf_token}" \
-          --header "Content-Type: application/vnd.api+json" \
-          https://app.terraform.io/api/v2/users/"${user_id}" |
-          jq -r '.data.attributes.username')"
-        printf '%s %s\n' "${organization_membership_id}" "${username}"
-      done
+      jq -r '.data.attributes.email')"
+    printf '%s %s\n' "${email}" "${organization_membership_id}"
   done
 
-# Display the variable set IDs.
-printf '\n%s\n' "Variable Set ID         Variable Set Name"
-printf '%s\n' "----------------------- ---------------------------"
-curl --silent \
-  --header "Authorization: Bearer ${tf_token}" \
-  --header "Content-Type: application/vnd.api+json" \
-  https://app.terraform.io/api/v2/organizations/"${organization_name}"/varsets |
-  jq -r '.data[].id' |
-  while read -r variable_set_id; do
-    variable_set_name="$(curl --silent \
-      --header "Authorization: Bearer ${tf_token}" \
-      --header "Content-Type: application/vnd.api+json" \
-      https://app.terraform.io/api/v2/varsets/"${variable_set_id}" |
-      jq -r '.data.attributes.name')"
-    printf '%s %s\n' "${variable_set_id}" "${variable_set_name}"
-  done
-
-# Display the project IDs.
-printf '\n%s\n' "Project ID           Project Name"
-printf '%s\n' "-------------------- ---------------"
 curl --silent \
   --header "Authorization: Bearer ${tf_token}" \
   --header "Content-Type: application/vnd.api+json" \
@@ -79,9 +61,6 @@ curl --silent \
     printf '%s %s\n' "${project_id}" "${project_name}"
   done
 
-# Display the workspace IDs.
-printf '\n%s\n' "Workspace ID        Workspace Name"
-printf '%s\n' "------------------- -------------------"
 curl --silent \
   --header "Authorization: Bearer ${tf_token}" \
   --header "Content-Type: application/vnd.api+json" \
@@ -94,4 +73,18 @@ curl --silent \
       https://app.terraform.io/api/v2/workspaces/"${workspace_id}" |
       jq -r '.data.attributes.name')"
     printf '%s %s\n' "${workspace_id}" "${workspace_name}"
+  done
+
+curl --silent \
+  --header "Authorization: Bearer ${tf_token}" \
+  --header "Content-Type: application/vnd.api+json" \
+  https://app.terraform.io/api/v2/organizations/"${organization_name}"/varsets |
+  jq -r '.data[].id' |
+  while read -r variable_set_id; do
+    variable_set_name="$(curl --silent \
+      --header "Authorization: Bearer ${tf_token}" \
+      --header "Content-Type: application/vnd.api+json" \
+      https://app.terraform.io/api/v2/varsets/"${variable_set_id}" |
+      jq -r '.data.attributes.name')"
+    printf '%s %s\n' "${variable_set_id}" "${variable_set_name}"
   done
